### ISSUE TITLE
Pair to pair review for Week3-D3

### ISSUE THREAD

**Issue by hiwina** [felixDev22/Mobile-first-D3#10]
**Great job you have done!**

- [ ] Kindly use your desktop navigation menu instead of creating a new one for the mobile.
- [ ] no any other issue so far. 😄 👍

**Comment by omarsalem7** [comment]
Hi @felixDev22 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 💀 
You have submitted an issue instead of a pull request for the mobile menu milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by felixDev22** [comment]
Thank you. Changes implemented
